version: '3'

services:
  flask-app:
    build: .
    expose:
      - "5000"  # direct port to the flask application
      - "8000"  # user reverse proxy for fast access to static data
    ports:
      - "8000:8000"
      - "5000:5000"
